apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: toql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: toql
    app.kubernetes.io/part-of: byoc-app-pokg
  name: toql
spec:
  rules:
  - host: toql-byoc-unei-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-47cdl.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: toql
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
